language: node_js

os:
  - linux

dist:
  - trusty

node_js:
  - '10'
  - '12'

install:
  - npm install

branches:
  only:
    - main

script:
  - npm run build

cache:
  directories:
    - node_modules
