name: master

on:
  push:
    branches:
      - 'master'

jobs:
  setup:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{secrets.RUNNER_GITHUB_TOKEN}}
    steps:
      - uses: actions/checkout@v3
      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: bokker/thumba
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - run: |
            git config --global user.email "bokker11@hotmail.com"
            git config --global user.name "Norbert Takács"
      - run: npm install
      - run: node node_modules/.bin/release-it --ci

      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@master

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: bokker/thumba:latest,bokker/thumba:${{ steps.package-version.outputs.current-version}}
